# Generated by Django 4.2 on 2024-03-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='shop.tag'),
        ),
    ]
